package ca.mcmaster.magarveylab.enums.domains;

import ca.mcmaster.magarveylab.enums.DomainFamilies;

public enum RegulatorDomains implements DomainType {

	// round 1
	AbrC1("AbrC1","Sensory kinase of S. coelicolor.  Coexpressed with AbrC2. Have negative affect on antibiotic production. Might have phosphatase activity. ","AbrC1.hmm",850),
	AbrC2("AbrC2","Sensory kinase of S. coelicolor.  Coexpressed with AbrC1","AbrC2.hmm",900),
	AbrC3("AbrC3","Response regulator of S. coelicolor. Positive regulator of RED, CDA, ACT and morphological change.","AbrC3.hmm",470),
	AbsA1("AbsA1","Sensor kinase. Global negative regulation of Streptomyces coelicolor antibiotic synthesis","AbsA1.hmm",1200),
	AbsA2("AbsA2","Response regulator. Global negative regulation of Streptomyces coelicolor antibiotic synthesis","AbsA2.hmm",400),
	AcrR("AcrR","Regpressor of pyochelin biosynthesis in Streptomyces scabies 87-22","AcrR.hmm",470),
	ActII_orf4("ActII-orf4","Pathway specific activator of actinorhodin biosynthesis in Streptomyces coelicolor","ActII-orf4.hmm",500),
	ActR("ActR","TetR-like protein that represses the adjacent actA operon, encoding the ACT export system (Actinorhodin)","ActR.hmm",500),
	AdpA("AdpA","Global activator of Strp production in S. griseus (activates StrR))","AdpA.hmm",880),
	AfsA("AfsA","A-factor biosynthesis enzyme","AfsA.hmm",600),
	AfsQ1("AfsQ1","Response regulator for S. coelicolor. Positive regulator of RED, ACT, CDA and yCPK","AfsQ1.hmm",498),
	AfsQ2("AfsQ2","Histidine kinase in S. coelicolor","AfsQ2.hmm",1100),
	AknO("AknO","Regulator of aclacinomycin in Streptomyces galilaeus","AknO.hmm",380),
	AlpU("AlpU","DNA transcription regulator - SARP","AlpU.hmm",300),
	AlpV("AlpV","DNA transcription regulator - SARP","AlpV.hmm",420),
	AlpW("AlpW","Repressor of Alp production in S. ambofaciens, Located in the alpomycin biosynthesis cluster and involved in the regulation of kinamycin biosynthesis; similar to gamma-butyrolactone receptors","AlpW.hmm",167),
	ArpA("ArpA","GBL receptor type regulator. Repressor in Strp production of S. griseus, Involved in the regulation of antibiotic production and sporulation","ArpA.hmm",500),
	AsfR("AsfR","DNA transcription regulator - LysR-type","AsfR.hmm",1200),
	AsuR5("AsuR5","Activator of asukamycin in Streptomyces nodosus subsp. asukaensis","AsuR5.hmm",190),
	AurD("AurD","Activator of aureothin biosynthesis in Streptomyces thioluteus","AurD.hmm",170),
	AveR("AveR","LAL-type regulator. Involved in avermectin synth. in S. avermectillis","AveR.hmm",1500),
	BafG("BafG","Activator of bafilomycin biosynthesis in Streptomyces lohii","BafG.hmm",900),
	BarA("BarA","TetR-type regulator. Repressor of virginiamycin synth in S. virginiae","BarA.hmm",205),
	BarX("BarX","GBL-receptor regulator. Possitive regulator of virginiamycin biosynthesis in S. virginiae.","BarX.hmm",275),
	BldD("BldD","Global regulator of coronafacic acid like comound biosynthesis in Streptomyces scabies 87-22","BldD.hmm",377),
	CcaR("CcaR","Activator of cephamycin & clavulanic acid biosynth. in S. clavuligerus","CcaR.hmm",400),
	ChlF2("ChlF2","Two-component <br> Response regulator for chlorothricin biosynthesis in Streptomyces antibioticus","ChlF2.hmm",370),
	CinR1("CinR1","Activator of cinnamycin biosynthesis in Streptomyces cinnamoneus","CinR1.hmm",205),
	CmmR("CmmR","Hydrolase","CmmR.hmm",270),
	CphR("CphR","Activator of cephamycin c prod. in S. cattleya","CphR.hmm",450),
	Cpp1("Cpp1","Activator of pristinamycin biosynth. in S. pristinaespiralis","Cpp1.hmm",500),
	Crp("Crp","DNA transcription regulator - cAMP Kinase in ACT, RED and CDA biosynthesis in S. coelicolor","Crp.hmm",301),
	CutR("CutR","Two-component <br> Response regulator. neg. reg. of ACT production in S. lividans & coelicolor. Alters copper metabolism","CutR.hmm",180),
	CutS("CutS","Two-component <br> Sensor kinase in S. lividans & coelicolor","CutS.hmm",865),
	Cvm7P("Cvm7P","DNA transcription regulator (+) - BTAD-type","Cvm7P.hmm",1500),
	DraK("DraK","Two-component <br> Histidine kinase of S. coelicolor. ","DraK.hmm",850),
	DraR("DraR(CheY)","Two-component <br>  Response regulator in S. coelicolor. Positive regulator of ACT, negative of RED and yCPK: DraK","DraR.hmm",500),
	EcrA1("EcrA1","Two-component <br> Sensory kinase in S. coelicolor.","EcrA1.hmm",750),
	EcrA2("EcrA2","Two-component <br> Response regulator in S. coelicolor. Positive reg. in RED production.","EcrA2.hmm",435),
	EcrE2("EcrE2","Two-component <br> Response regulator. Positive reg. in RED prod. in S. coelicolor","EcrE2.hmm",450),
	FarA("FarA","GBL receptor <br> Autoregulator in S. lavendulae showdomycin production","FarA.hmm",250),
	FrnG("FrnG","Activator of frenolicin biosynthesis in Streptomyces roseofulvus","FrnG.hmm",215),
	FscRII("FscRII","Response regulator- LuxR-type","FscRII.hmm",1500),
	FscRIII("FscRIII","Response regulator- LuxR-type","FscRIII.hmm",1500),
	FscRIV("FscRIV","Response regulator- LuxR-type","FscRIV.hmm",1500),
	MtmR("MtmR","Activator of mithramycin biosynthesis in Streptomyces argillaceus","MtmR.hmm",200),
	NanR2("NanR2","Activator of nanchangmycin biosynthesis in Streptomyces nangchangensis","NanR2.hmm",400),
	NosP("NosP","Activator of nosiheptide in Streptomyces actuosus","NosP.hmm",250),
	OzmU("OzmU","DNA transcription regulator (+) - BTAD-type","OzmU.hmm",1000),
	PapR2("PapR2","Activator of pristinamycin biosynth in S. pristinaespiralis","PapR2.hmm",600),
	PapR4("PapR4","Activator of pristinamycin biosynth in S. pristinaespiralis","PapR4.hmm",333),
	PapR6("PapR6","Two-component <br> Response regulator in pristinamycin biosynth. in S. pristinaespiralis","PapR6.hmm",500),
	PieR("PieR","Activator of piericidin biosynthesis in Streptomyces piemogenus","PieR.hmm",200),
	PimM("PimM","Activator of pimaricin biosynthesis in S. natalensis","PimM.hmm",350),
	PimR("PimR","LAL-type regulator. Activates PimE in S. natalensis (regulates pimaricin biosynthesis)","PimR.hmm",1700),
	PlaR("PlaR","Putative regulator in Streptomyces sp. strain Tu6071","PlaR.hmm",500),
	PolR("PolR","Activator of polyoxin biosynthesis in Streptomyces cacaoi subsp. asoensis","PolR.hmm",500),
	RapA1("RapA1","Two-component <br> Response regulator in S. coelicolor. Positive regulator in ACT and yCPK biosynthesis","RapA1.hmm",460),
	RapA2("RapA2","Two-component <br> Sensory kinase in S. coelicolor.","RapA2.hmm",800),
	RedD("RedD","Activator of undecylprodigiosin in Streptomyces coelicolor","RedD.hmm",600),
	RedZ("RedZ","Regulator of undecylprodigiosin in Streptomyces coelicolor","RedZ.hmm",350),
	Rkl("Rkl","DNA transcription regulator - TetR","Rkl.hmm",250),
	RphD("RphD","Activator of prodigiosin biosynthesis in Streptomyces griseoviridis","RphD.hmm",230),
	RubS("RubS","Activator of rubromycin biosynthesis in Streptomyces collinus","RubS.hmm",400),
	SamR0468("SamR0468","Response regulator- LuxR-type (CheY superfamily)","SamR0468.hmm",250),
	SanR1("SanR1","Activator of A-74528 biosynthesis in Streptomyces sp. SANK 61196","SanR1.hmm",390),
	ScbA("ScbA","A-factor biosynthesis enzyme","ScbA.hmm",550),
	ScbR("ScbR","Regulator  in RED prod. in S. coelicolor, SCB1","ScbR.hmm",350),
	Sco5784("Sco5784","Histidine kinase","Sco5784.hmm",600),
	Sco5785("Sco5785","Response regulator- LuxR-type (CheY superfamily)","Sco5785.hmm",440),
	Sky44("Sky44","Activator of skyllamycin production in Streptomyces sp. strain Acta 2987","Sky44.hmm",470),
	SscR("SscR","GBL-receptor regulator. Regulator of thaxtomin A biosynthesis in Streptomyces scabies NBRC 12914","SscR.hmm",350),
	StrR("StrR","Pathway specific regulator of streptomycin biosynth. in S. griseus","StrR.hmm",600),
	TarA("TarA","GBL-receptor regulator. Negative regulator of nikkomycin production in S. tendae","TarA.hmm",300),
	ThnI("ThnI","Lys-R regulator. Regulator of thienamycin production in S. cattleya ","ThnI.hmm",750),
	ThnU("ThnU","Activator of cephamycin c prod. in S. cattleya","ThnU.hmm",450),
	Tyl_type_Regulator("Tyl-type_Regulator","DNA transcription regulator (-) - GBL receptor ","Tyl-type_Regulator.hmm",110),
	VmsT("VmsT","Pathway specific regulator of virginiamycin production in S. virginiae","VmsT.hmm",150),
	
	// round 2
	AbyC("AbyC","TetR-type regulator <br> Located in the abyssomicin biosynthesis cluster; predicted to regulate abyD encoding a MFS export pump; mutation decreases abyssomicin synthesis of Verrucosispora maris AB-18-032: ","AbyC.hmm",320),
	AcmP("AcmP","TetR-type regulator <br> Located in the actinomycin D biosynthesis cluster of Streptomyces chrysomallus ATCC 11523","AcmP.hmm",380),
	AcmU("AcmU","TetR-type regulator <br> Located in the actinomycin D biosynthesis cluster of Streptomyces chrysomallus ATCC 11523","AcmU.hmm",400),
	AcnR("AcnR","TetR-type regulator <br> Regulates the aconitase (acn) gene inf Corynebacterium glutamicum","AcnR.hmm",350),
	AcrRe("AcrRe","TetR-type regulator <br> Regulator of the AcrAB multidrug efflux pump of E. coli: Rhodamine 6G, ethidium, proflavine","AcrRe.hmm",475),
	AcuR("AcuR","TetR-type regulator <br> Putative repressor for genes involved in dimethylsulfoniopropionate and acrylate catabolism in Alcaligenes faecalis","AcuR.hmm",300),
	AcuRs("AcuRs","TetR-type regulator <br> Regulates expression of AcuI and DddL involved in dimethylsulfoniopropionate and acrylate catabolism in Rhodobacter sphaeroides: Acrylate","AcuRs.hmm",450),
	AdeN("AdeN","TetR-type regulator <br> Regulator of the AdeIJK efflux pump of Acinetobacter baumannii","AdeN.hmm",420),
	AefR("AefR","TetR-type regulator <br> Regulates AHL production and is required for plant colonization of Pseudomonas syringae","AefR.hmm",370),
	AguR("AguR","TetR-type regulator <br> Regulates AguBA required for agmatine utilization of Pseudomonas aeruginosa PAO1: Agmatine","AguR.hmm",425),
	AmeR("AmeR","TetR-type regulator <br> Regulates the tripartite RND exporter AmeABC of Agrobacterium tumefaciens","AmeR.hmm",400),
	AmiP("AmiP","TetR-type regulator <br> Located in the amicetin biosynthesis cluster of Streptomyces vinaceus-drappus","AmiP.hmm",170),
	AmtR("AmtR","TetR-type regulator <br> Global regulator of nitrogen control metabolism of Corynebacterium glutamicum: GlnK","AmtR.hmm",450),
	ArpR("ArpR","TetR-type regulator <br> Regulates the ArpABC efflux pump involved in the export of multiple antibiotics of Pseudomonas putida S12","ArpR.hmm",400),
	Asm2("Asm2","TetR-type regulator <br> Located in the ansamitocin biosynthesis cluster and involved in the regulation of ansamitocin biosynthesis of Actinosynnema pretiosum","Asm2.hmm",435),
	Asm29("Asm29","TetR-type regulator <br> Located in the ansamitocin biosynthesis cluster and involved in the regulation of ansamitocin biosynthesis of Actinosynnema pretiosum: ","Asm29.hmm",440),
	AtuR("AtuR","TetR-type regulator <br> Regulates genes required for acyclic terpene utilization of Pseudomonas aeruginosa        ","AtuR.hmm",425),
	Aur1B("Aur1B","TetR-type regulator <br> Located in the auricin biosynthesis cluster of Streptomyces aureofaciens CCM 3239","Aur1B.hmm",180),
	Aur1R("Aur1R","TetR-type regulator <br> Located in the auricin biosynthesis cluster; similar to gamma-butyrolactone receptors of Streptomyces aureofaciens CCM 3239","Aur1R.hmm",200),
	AvaR1("AvaR1","TetR-type regulator <br> Regulator of avermectin biosynthesis; similar to gamma-butyrolactone receptors of Streptomyces avermitilis: Avenolide","AvaR1.hmm",450),
	AvaR2("AvaR2","TetR-type regulator <br> Similar to gamma-butyrolactone receptors of Streptomyces avermitilis","AvaR2.hmm",400),
	Azi42("Azi42","TetR-type regulator <br> Located adjacent to the azinomycin B biosynthetic gene cluster; thought to be beyond the boundaries of the cluster of Streptomyces sahachiroi","Azi42.hmm",420),
	BarZ("BarZ","TetR-type regulator <br> Located in the virginiamycin biosynthesis cluster; similar to gamma-butyrolactone-binding proteins of Streptomyces virginiae","BarZ.hmm",80),
	BdcR("BdcR","TetR-type regulator <br> Regulator of BdcA expression of E. coli K12","BdcR.hmm",400),
	BecM("BecM","TetR-type regulator <br> Located in the biosynthesis cluster for macrolactam BE-14106 biosynthesis of Streptomyces sp. strain DSM 21069","BecM.hmm",400),
	BepR("BepR","TetR-type regulator <br> Regulator of the BepDE efflux pump of Brucella suis: Deoxycholate","BepR.hmm",470),
	BetI("BetI","TetR-type regulator <br> Regulates expression of BetT, BetA, and BetB required for the synthesis of glycine betaine from choline of E. coli K12: Choline","BetI.hmm",450),
	BioQ("BioQ","TetR-type regulator <br> Regulates biotin biosynthesis and import of Corynebacterium resistens strain DSM 45100 ","BioQ.hmm",300),
	BpeR("BpeR","TetR-type regulator <br> Regulates the BpeAB-OprB multidrug efflux pump of Burkholderia pseudomallei","BpeR.hmm",450),
	BreR("BreR","TetR-type regulator <br> Regulates the BreAB efflux pump in response to bile of Vibrio cholerae: Deoxycholate","BreR.hmm",400),
	Brp("Brp","TetR-type regulator <br> Gamma-butyrolactone receptor involved in the regulation of clavulanic acid and cephamycin C biosynthesis of Streptomyces clavuligerus","Brp.hmm",450),
	BrtA("BrtA","TetR-type regulator <br> Regulator of the MdrT efflux pump of Listeria monocytogenes: Cholate","BrtA.hmm",280),
	BspR("BspR","TetR-type regulator <br> Involved in regulating type III secretion systems of Burkholderia pseudomallei","BspR.hmm",450),
	BtrR1("BtrR1","TetR-type regulator <br> Located in the butirosin biosynthesis cluster and involved in regulation of Bacillus circulans","BtrR1.hmm",100),
	CalR1("CalR1","TetR-type regulator <br> Located in the calicheamicin biosynthesis cluster of Micromonospora echinospora","CalR1.hmm",245),
	CampR("CampR","TetR-type regulator <br> Divergent to camK (6-oxocamphor hydrolase) of Rhodococcus sp. strain NCIMB 9784","CampR.hmm",130),
	CamR("CamR","TetR-type regulator <br> Regulator of camphor degradation of Pseudomonas putida","CamR.hmm",100),
	CasR("CasR","TetR-type regulator <br> Regulator of CasA required for colonization and infection of the host of Rhizobium etli","CasR.hmm",250),
	CgmR("CgmR","TetR-type regulator <br> Multidrug resistance-related transcription factor of Corynebacterium glutamicum: Ethidium bromide, malachite green","CgmR.hmm",300),
	ChlF1("ChlF1","TetR-type regulator <br> Located in the chlorothricin biosynthetic gene cluster of Streptomyces antibioticus","ChlF1.hmm",190),
	ChryX5("ChryX5","TetR-type regulator <br> Located in the chrysomycin biosynthesis cluster; a homolog is not present in the cluster for the related molecule ravidomycin of Streptomyces albaduncus","ChryX5.hmm",300),
	CifR("CifR","TetR-type regulator <br> Regulator of the Cif toxin of Pseudomonas aeruginosa: Epibromohydrin","CifR.hmm",350),
	CmeR("CmeR","TetR-type regulator <br> Regulator of the CmeABC efflux pump of Campylobacter jejuni: Taurocholate, cholate, salicylate","CmeR.hmm",400),
	CmtI("CmtI","TetR-type regulator <br> Putative regulator of operons required for p-cymene/p-cumate degradation of Pseudomonas putida","CmtI.hmm",75),
	CmtR("CmtR","TetR-type regulator <br> Putative regulator of operons required for p-cymene/p-cumate degradation of Pseudomonas putida","CmtR.hmm",75),
	ComR("ComR","TetR-type regulator <br> Regulator of ComC involved in copper permeability of E. coli K12: Copper","ComR.hmm",450),
	DarR("DarR","TetR-type regulator <br> First cyclic-di-AMP-responsive transcription factor to be identified in bacteria of Mycobacterium smegmatis: Cyclic-di-AMP","DarR.hmm",650),
	DddH("DddH","TetR-type regulator <br> Putative regulator of genes required for dimethylsulfoniopropionate and acrylate catabolism of Halomonas sp. strain HTNK1","DddH.hmm",270),
	DesT("DesT","TetR-type regulator <br> Regulates the expression of the DesCB acyl-CoA desaturase operon of Pseudomonas aeruginosaj: Oleate (corepressor), stearate (inducer)","DesT.hmm",400),
	DhaR("DhaR","TetR-type regulator <br> Regulator of haloalkane dehalogenase (DhaA) of Rhodococcus rhodochrous","DhaR.hmm",1150),
	DhaS("DhaS","TetR-type regulator <br> Regulator of the dha operon; functions as a transcriptional activator of Lactococcus lactis: DhaQ-dihydroxyacetone complex","DhaS.hmm",250),
	Ecm10("Ecm10","TetR-type regulator <br> Located in the echinomycin biosynthesis cluster of Streptomyces lasaliensis","Ecm10.hmm",300),
	EmhR("EmhR","TetR-type regulator <br> Regulates the EmhABC efflux pump that influences production of 2,4-diacetylphloroglucinol and is required for phenanthrene, anthracene, and fluoranthene efflux of Pseudomonas fluorescens","EmhR.hmm",390),
	EncS("EncS","TetR-type regulator <br> Located in the enterocin biosynthesis gene cluster of Streptomyces maritimus","EncS.hmm",300),
	EnvR("EnvR","TetR-type regulator <br> Divergent to the AcrEF efflux pump; may function as a switch for the alternative expression of AcrAB and AcrEF efflux pumps of E. coli","EnvR.hmm",400),
	EsmT4("EsmT4","TetR-type regulator <br> Located in the esmeraldin biosynthesis cluster of Streptomyces antibioticus Tu 2706","EsmT4.hmm",200),
	EthR("EthR","TetR-type regulator <br> Regulator of ethA encoding a monooxygenase required for the activation of ethionamide of Mycobacterium tuberculosis: Hexadecyl octanoate","EthR.hmm",400),
	FabR("FabR","TetR-type regulator <br> Regulator of genes required for unsaturated fatty acid synthesis of Escherichia coli: Unsaturated thioesters","FabR.hmm",480),
	Fad35R("Fad35R","TetR-type regulator <br> Regulator of Fad35 acyl-CoA synthetase of Mycobacterium tuberculosis: Palmitoyl-CoA","Fad35R.hmm",400),
	FadRP("FadRP","TetR-type regulator <br> Regulates fad genes required for fatty acid degradation of Pseudonocardia autotrophica","FadRP.hmm",150),
	FadRT("FadRT","TetR-type regulator <br> Regulator of genes required for fatty acid degradation of Thermus thermophilus: Medium to long (C10 to C18) straight-chain fatty acyl-CoAs","FadRT.hmm",350),
	FasR("FasR","TetR-type regulator <br> Regulator of accD1 and fasA expression required for lipid synthesis of Corynebacterium diphtheriae","FasR.hmm",420),
	FrrA("FrrA","TetR-type regulator <br> Regulator of the FreABC efflux pump of Bradyrhizobium japonicum","FrrA.hmm",250),
	HapR("HapR","TetR-type regulator <br> Master quorum-sensing regulator of Vibrio cholerae","HapR.hmm",270),
	HemR("HemR","TetR-type regulator <br> Possible regulator of hem gene expression required for the conversion of glutamate to protoheme of Propionibacterium freudenreichii","HemR.hmm",275),
	HlyIIR("HlyIIR","TetR-type regulator <br> Regulator of hemolysin II expression of Bacillus cereus","HlyIIR.hmm",300),
	HnoR("HnoR","TetR-type regulator <br> Repressor of 6-hydroxy-d-nicotine oxidase of Arthrobacter nicotinovorans: 6-Hydroxy-d- and 6-hydroxy-l-nicotine","HnoR.hmm",77),
	HrtR("HrtR","TetR-type regulator <br> Regulator of the HrtB-HtrA transporter of Lactococcus lactis: Heme","HrtR.hmm",210),
	IcaR("IcaR","TetR-type regulator <br> Regulator of the ica operon required for biofilm formation of Staphylococcus epidermidis","IcaR.hmm",170),
	IfeR("IfeR","TetR-type regulator <br> Regulator of the IfeAB efflux pump of Agrobacterium tumefaciens","IfeR.hmm",130),
	JadR("JadR","TetR-type regulator <br> Located in the jadomycin biosynthesis cluster of Streptomyces venezuelae","JadR.hmm",360),
	KanG("KanG","TetR-type regulator <br> Located near the kanamycin biosynthesis cluster but probably beyond cluster boundaries of Streptomyces kanamyceticus","KanG.hmm",170),
	KijA8("KijA8","TetR-type regulator <br> Located in the kijanimicin biosynthesis cluster of Actinomadura kijaniata: Kijanimicin","KijA8.hmm",160),
	KijC5("KijC5","TetR-type regulator <br> Located in the kijanimicin biosynthesis cluster of Actinomadura kijaniata","KijC5.hmm",150),
	KijR("KijR","TetR-type regulator <br> Regulator of KijX expression and kijanimicin resistance of Streptomyces coelicolor: Kijanimicin, saccharocarcins A and B","KijR.hmm",390),
	KinR("KinR","TetR-type regulator <br> Located in the kinamycin biosynthesis cluster of Streptomyces murayamaensis","KinR.hmm",140),
	KirRII("KirRII","TetR-type regulator <br> Located in the kirromycin biosynthesis cluster of Streptomyces collinus","KirRII.hmm",230),
	KsbA("KsbA","TetR-type regulator <br> Gamma-butyrolactone receptor protein; involved in regulating bafilomycin biosynthesis of Kitasatospora setae: GBLs","KsbA.hmm",240),
	KstR("KstR","TetR-type regulator <br> Regulator of lipid metabolism of Mycobacterium tuberculosis","KstR.hmm",465),
	KstR2("KstR2","TetR-type regulator <br> Regulator of cholesterol metabolism of Mycobacterium tuberculosis","KstR2.hmm",430),
	LanK("LanK","TetR-type regulator <br> Located in the landomycin biosynthetic pathway of Streptomyces cyanogenus: Landomycin A and intermediates","LanK.hmm",200),
	Lct13("Lct13","TetR-type regulator <br> Putative gamma-butyrolactone receptor protein; located in the lactonamycin biosynthesis cluster of Streptomyces rishiriensis","Lct13.hmm",250),
	Lct14("Lct14","TetR-type regulator <br> Putative gamma-butyrolactone receptor protein; located in the lactonamycin biosynthesis cluster of Streptomyces rishiriensis","Lct14.hmm",100),
	LfrR("LfrR","TetR-type regulator <br> Regulator of LfrA multidrug efflux pump of Mycobacterium smegmatis: Proflavine","LfrR.hmm",300),
	LitR("LitR","TetR-type regulator <br> Involved in regulating luminescence and symbiotic light organ colonization of Vibrio fischeri","LitR.hmm",320),
	LiuQ("LiuQ","TetR-type regulator <br> Regulator of branched-chain amino acid degradation of Burkholderia ambifaria AMMD","LiuQ.hmm",400),
	LmrA("LmrA","TetR-type regulator <br> Regulator of the LmrB efflux pump of Bacillus subtilis: Flavonoids (quercetin, fisetin, galangin, catechin, coumestrol, genistein)","LmrA.hmm",230),
	LplR("LplR","TetR-type regulator <br> Regulator of l-pantoyl lactone dehydrogenase gene expression of Rhodococcus erythropolis","LplR.hmm",350),
	LuxR("LuxR","TetR-type regulator <br> Global regulator of Vibrio harveyi","LuxR.hmm",300),
	LuxT("LuxT","TetR-type regulator <br> Global regulator of Vibrio harveyi","LuxT.hmm",280),
	McbR("McbR","TetR-type regulator <br> Global regulator of l-methionine and l-cysteine biosynthesis of Corynebacterium glutamicum: S-Adenosylhomocysteine","McbR.hmm",400),
	Mce3R("Mce3R","TetR-type regulator <br> Putative regulator of lipid metabolism of Mycobacterium tuberculosis","Mce3R.hmm",800),
	MdoR("MdoR","TetR-type regulator <br> Regulator of genes required for methanol oxidation of Mycobacterium sp. strain JC1","MdoR.hmm",150),
	MedORF28("MedORF28","TetR-type regulator <br> Located in the medermycin biosynthesis cluster of Streptomyces sp. strain AM-7161","MedORF28.hmm",300),
	MepR("MepR","TetR-type regulator <br> Regulates efflux pump involved in toluene resistance of Pseudomonas putida","MepR.hmm",400),
	MerO("MerO","TetR-type regulator <br> Located in the meridamycin biosynthesis cluster of Streptomyces sp. strain NRRL 30748","MerO.hmm",170),
	MexZ("MexZ","TetR-type regulator <br> Regulates the MexXY (AmrAB) exporter involved in aminoglycoside resistance of Pseudomonas aeruginosa","MexZ.hmm",300),
	MlaM("MlaM","TetR-type regulator <br> Located in the biosynthetic gene cluster for the macrocyclic lactam ML-449 of Streptomyces sp. strain MP39-85","MlaM.hmm",200),
	MmyR("MmyR","TetR-type regulator <br> Represses methylenomycin through inhibition of mmyB in S. coelicolor: (+) riggered by either of two environmental signals: alanine growth-rate-limiting conditions and/or an acidic pH shock.","MmyR.hmm",200),
	MnbR("MnbR","TetR-type regulator <br> Putative regulator of mnb operon required for 3-nitrobenzoate oxidation of Comamonas sp. strain JS46","MnbR.hmm",80),
	MonRII("MonRII","TetR-type regulator <br> Located in the monensin biosynthesis locus of Streptomyces cinnamonensis","MonRII.hmm",160),
	MphR("MphR","TetR-type regulator <br> Regulator of macrolide resistance of E. coli: 14-membered macrolides (erythromycin, oleandomycin)","MphR.hmm",150),
	MSMEG_6564("MSMEG_6564","TetR-type regulator <br> Global regulator of DNA repair genes of Mycobacterium smegmatis","MSMEG_6564.hmm",300),
	MtrR("MtrR","TetR-type regulator <br> Regulator of the mtr efflux pump of Neisseria gonorrhoeae","MtrR.hmm",350),
	NalC("NalC","TetR-type regulator <br> Indirect regulator of the MexAB-OprM efflux pump through regulation of ArmR expression of Pseudomonas aeruginosa","NalC.hmm",350),
	NalD("NalD","TetR-type regulator <br> Regulator of the MexAB-OprM efflux pump of Pseudomonas aeruginosa","NalD.hmm",350),
	NapR3("NapR3","TetR-type regulator <br> Located in the napyradiomycin biosynthesis cluster of Streptomyces aculeolatus","NapR3.hmm",170),
	NapR7("NapR7","TetR-type regulator <br> Located in the napyradiomycin biosynthesis cluster of Streptomyces aculeolatus","NapR7.hmm",150),
	NemR("NemR","TetR-type regulator <br> Regulator of N-ethylmaleimide reductase of E. coli: N-Ethylmaleimide and other Cys modification reagents","NemR.hmm",400),
	NfxB("NfxB","TetR-type regulator <br> Regulator of the MexCD-OprJ efflux pump of Pseudomonas aeruginosa","NfxB.hmm",300),
	NicS("NicS","TetR-type regulator <br> Regulator of genes required for nicotinic acid degradation of Pseudomonas putida: Nicotinic acid and hydroxynicotinic acid","NicS.hmm",360),
	NonG("NonG","TetR-type regulator <br> Located near the nonactin biosynthesis cluster but probably beyond cluster boundaries of Streptomyces griseus","NonG.hmm",380),
	OpaR("OpaR","TetR-type regulator <br> Global regulator of Vibrio parahaemolyticus","OpaR.hmm",420),
	OvmY("OvmY","TetR-type regulator <br> Located in the oviedomycin biosynthesis cluster of Streptomyces antibioticus","OvmY.hmm",300),
	PaaR("PaaR","TetR-type regulator <br> Regulator of genes required for phenyl acetic acid degradation of Deinococcus maricopensis","PaaR.hmm",150),
	PG1181("PG1181","TetR-type regulator <br> Expressed in response to NO stress of Porphyromonas gingivalis","PG1181.hmm",250),
	PgaY("PgaY","TetR-type regulator <br> Located in the pga angucyclinone biosynthesis cluster of Streptomyces sp. strain PGA64","PgaY.hmm",150),
	PhaD("PhaD","TetR-type regulator <br> Regulator of genes required for polyhydroxyalkanoate metabolism of Pseudomonas putida","PhaD.hmm",800),
	PhlF("PhlF","TetR-type regulator <br> Located in the 2,4-diacetylphloroglucinol biosynthesis cluster of Pseudomonas fluorescens: 2,4-Diacetylphloroglucinol (inducer), salicylate (corepressor)        ","PhlF.hmm",250),
	PhlH("PhlH","TetR-type regulator <br> Located in the 2,4-diacetylphloroglucinol biosynthesis cluster of Pseudomonas fluorescens","PhlH.hmm",350),
	PigZ("PigZ","TetR-type regulator <br> Regulator of the ZrpADBC efflux pump of Serratia sp. strain ATCC 39006","PigZ.hmm",250),
	PksA("PksA","TetR-type regulator <br> Located in the bacillaene biosynthesis cluster of Bacillus subtilis","PksA.hmm",300),
	PlaR2("PlaR2","TetR-type regulator <br> Located in the phenalinolactone biosynthesis cluster of Streptomyces sp. strain Tu6071","PlaR2.hmm",370),
	PltZ("PltZ","TetR-type regulator <br> Located in the pyoluteorin biosynthesis cluster of Pseudomonas sp. strain M18","PltZ.hmm",250),
	PmeR("PmeR","TetR-type regulator <br> Regulator of MexAB-OprM of Pseudomonas syringae: Flavonoids","PmeR.hmm",350),
	PsbI("PsbI","TetR-type regulator <br> Regulator of p-cumate catabolism of Rhodopseudomonas palustris: p-Cumate","PsbI.hmm",150),
	PsrA("PsrA","TetR-type regulator <br> Regulator of the &beta;-oxidation operon of Pseudomonas aeruginosa: Long-chain fatty acids","PsrA.hmm",485),
	Pyr27("Pyr27","TetR-type regulator <br> Located in the pyrrolomycin biosynthesis cluster of Actinosporangium vitaminophilum","Pyr27.hmm",170),
	Pyr3("Pyr3","TetR-type regulator <br> Located in the pyrrolomycin biosynthesis cluster of Actinosporangium vitaminophilum","Pyr3.hmm",130),
	PyrO("PyrO","TetR-type regulator <br> Located in the pyridomycin biosynthesis cluster; similar to gamma-butyrolactone receptors of Streptomyces pyridomyceticus","PyrO.hmm",170),
	QacR("QacR","TetR-type regulator <br> Regulator of the QacA efflux pump of Staphylococcus aureus: Rhodamine 6G, dequalinium, crystal violet, berberine, DiOC3, methyl green, benzalkonium, tetraphenylarsonium, nitidine, palmatine","QacR.hmm",100),
	QdoR("QdoR","TetR-type regulator <br> Regulator of quercetin dioxygenase QdoI (YxaG) of Bacillus subtilis: Flavonoids (quercetin, fisetin, tamarixetin, galangin, genistein, coumestrol)","QdoR.hmm",250),
	RamR("RamR","TetR-type regulator <br> Regulator of the RamA efflux pump; mutations in the RamR binding site result in a multidrug resistance phenotype of Salmonella enterica serovar Typhimurium","RamR.hmm",400),
	RefZ("RefZ","TetR-type regulator <br> Involved in the switch from medial to polar cell division of Bacillus subtilis","RefZ.hmm",350),
	RegE("RegE","TetR-type regulator <br> Located in (or adjacent to) the friulimicin biosynthesis cluster of Actinoplanes friuliensis","RegE.hmm",300),
	RemM("RemM","TetR-type regulator <br> Located in the resistomycin biosynthesis cluster of Streptomyces resistomycificus","RemM.hmm",130),
	RemQ("RemQ","TetR-type regulator <br> Located in the resistomycin biosynthesis cluster of Streptomyces resistomycificus","RemQ.hmm",145),
	RifQ("RifQ","TetR-type regulator <br> Located in the rifamycin biosynthesis cluster of Amycolatopsis mediterranei","RifQ.hmm",350),
	RmiR("RmiR","TetR-type regulator <br> Regulator of NodTch of Rhizobium etli","RmiR.hmm",350),
	RmrR("RmrR","TetR-type regulator <br> Regulator of the RmrAB efflux pump of Rhizobium etli","RmrR.hmm",430),
	RolR("RolR","TetR-type regulator <br> Regulator of resorcinol degradation of Corynebacterium glutamicum: Resorcinol","RolR.hmm",250),
	RphA3("RphA3","TetR-type regulator <br> Located in the prodigiosin biosynthesis cluster of Streptomyces griseoviridis","RphA3.hmm",150),
	RutR("RutR","TetR-type regulator <br> Regulator of pyrimidine synthesis of E. coli: Uracil","RutR.hmm",490),
	Rv3066("Rv3066","TetR-type regulator <br> Regulator of Mmr multidrug efflux pump of Mycobacterium tuberculosis: Ethidium","Rv3066.hmm",350),
	SACE_7040("SACE_7040","TetR-type regulator <br> Regulator of morphological differentiation of Saccharopolyspora erythraea","SACE_7040.hmm",320),
	SaqK("SaqK","TetR-type regulator <br> Located in the saquayamycin Z biosynthesis cluster of Micromonospora sp. strain Tu 6368","SaqK.hmm",200),
	SAV3818("SAV3818","TetR-type regulator <br> Global upregulator of antibiotic production in Streptomyces species of Streptomyces avermitilis","SAV3818.hmm",470),
	SbtR("SbtR","TetR-type regulator <br> Contains an intermolecular disulfide bridge that may be involved in ligand affinity of Thermus thermophilus HB8","SbtR.hmm",300),
	SCAB1401("SCAB1401","TetR-type regulator <br> Located in the pyochelin biosynthesis cluster of Streptomyces scabies","SCAB1401.hmm",400),
	SchA21("SchA21","TetR-type regulator <br> Located in the biosynthesis cluster for the angucyclinones Sch 47554 and Sch 47555 of Streptomyces sp. strain SCC-2136","SchA21.hmm",300),
	SchA4("SchA4","TetR-type regulator <br> Located in the biosynthesis cluster for the angucyclinones Sch 47554 and Sch 47555 of Streptomyces sp. strain SCC-2136","SchA4.hmm",460),
	SchR3("SchR3","TetR-type regulator <br> Located in the biosynthesis cluster for calcimycin of Streptomyces chartreusis","SchR3.hmm",170),
	SCO0253("SCO0253","TetR-type regulator <br> Regulator of SCO0252 of Streptomyces coelicolor: Tetracycline","SCO0253.hmm",300),
	SCO0332("SCO0332","TetR-type regulator <br> Regulator of SCO0330 of Streptomyces coelicolor","SCO0332.hmm",340),
	SCO1712("SCO1712","TetR-type regulator <br> Regulator of antibiotic production of Streptomyces coelicolor","SCO1712.hmm",390),
	SCO3201("SCO3201","TetR-type regulator <br> Regulator of antibiotic production of Streptomyces coelicolor","SCO3201.hmm",300),
	SczA("SczA","TetR-type regulator <br> Regulator of metal ion homeostasis of Streptococcus pneumoniae: Zn2+","SczA.hmm",300),
	SfmR1("SfmR1","TetR-type regulator <br> Located in the saframycin A biosynthesis cluster of Streptomyces lavendulae","SfmR1.hmm",200),
	SlgR1("SlgR1","TetR-type regulator <br> Located in the streptolydigin biosynthesis cluster of Streptomyces lydicus","SlgR1.hmm",250),
	SlmA("SlmA","TetR-type regulator <br> Nucleoid occlusion factor of E. coli: FtsZ","SlmA.hmm",440),
	SmcR("SmcR","TetR-type regulator <br> Global regulator of Vibrio vulnificus","SmcR.hmm",400),
	SmeT("SmeT","TetR-type regulator <br> Regulator of the SmeDEF efflux pump of Stenotrophomonas maltophilia: Triclosan","SmeT.hmm",250),
	SMU_1349("SMU_1349","TetR-type regulator <br> Regulator of the TnSmu2 operon, which contains a secondary metabolite biosynthesis gene cluster of Streptococcus mutans","SMU_1349.hmm",250),
	SngR("SngR","TetR-type regulator <br> Negative regulator of natamycin production in S. natalensis, Gamma-butyrolactone receptor protein involved in regulating natamycin biosynthesis and sporulation: (+) propanol, glucose (20g/L), potassium dihydrogen phosphate (0.05 g/L), mixture of beef extract and yeast extract (8 g/l and 2 g/l, respectively), 25 ml or 50 ml medium per flask, 250 rpm agitated culture, spore innoculum","SngR.hmm",200),
	SocA3("SocA3","TetR-type regulator <br> Involved in regulating morphological development of Myxococcus xanthus","SocA3.hmm",350),
	SrpR("SrpR","TetR-type regulator <br> Regulator of the SrpABC efflux pump of Pseudomonas putida: SrpS","SrpR.hmm",90),
	SrrA("SrrA","TetR-type regulator <br> Involved in the regulation of lankacidin and lankamycin biosynthesis along with SSRB, and C in S. rochei, Gamma-butyrolactone receptor protein involved in regulating lankacidin and lankamycin biosynthesis and sporulation","SrrA.hmm",250),
	SrrB("SrrB","TetR-type regulator <br> Involved in the regulation of lankacidin and lankamycin biosynthesis along with SSRA, and C in S. rochei","SrrB.hmm",150),
	SrrC("SrrC","TetR-type regulator <br> Involved in the regulation of lankacidin and lankamycin biosynthesis along with SSRA, and B in S. rochei","SrrC.hmm",130),
	SsfT2("SsfT2","TetR-type regulator <br> Located in the biosynthesis cluster for the polyketide SF2575 of Streptomyces sp. strain SF2575","SsfT2.hmm",195),
	Strop_2766("Strop_2766","TetR-type regulator <br> Located in the salinilactam biosynthesis cluster of Salinispora tropica","Strop_2766.hmm",300),
	TamK("TamK","TetR-type regulator <br> Located in the tirandamycin biosynthesis cluster of Streptomyces sp. strain 307-9","TamK.hmm",260),
	TcmR("TcmR","TetR-type regulator <br> Located in the tetracenomycin C biosynthesis cluster of Streptomyces glaucescens","TcmR.hmm",180),
	Tei8("Tei8","TetR-type regulator <br> Located in the teicoplanin biosynthesis cluster of Actinoplanes teichomyceticus","Tei8.hmm",300),
	Tmn21("Tmn21","TetR-type regulator <br> Located in the tetronomycin biosynthesis cluster of Streptomyces sp. strain NRRL 11266","Tmn21.hmm",105),
	TR("TR","TetR-type regulator <br> Putative regulator of macrolide resistance of Mycobacterium peregrinum","TR.hmm",300),
	TrdK("TrdK","TetR-type regulator <br> Negative regulator of tirandamycin biosynthesis in Streptomyces spp. (SCS1O1666): (+)glucose 10.0g, corn starch 10.0g, glycerol 10.0g, corn steep 2.5g, peptone 5.0g, yeast extract 2.0g, NaCl 1.0 g and CaCO3 3.0 g in 1 l distilled water, pH 7.2.","TrdK.hmm",250),
	Tsn22("Tsn22","TetR-type regulator <br> Located in the tetronasin biosynthesis cluster of Streptomyces longisporoflavus","Tsn22.hmm",105),
	TtgR("TtgR","TetR-type regulator <br> Regulator of the TtgABC efflux pump of Pseudomonas putida: Phloretin, naringenin, chloramphenicol, tetracycline, quercetin, luteolin","TtgR.hmm",350),
	TtgW("TtgW","TetR-type regulator <br> Divergent to the TtgGHI efflux pump but does not play a major role in regulation of Pseudomonas putida","TtgW.hmm",95),
	TvrR("TvrR","TetR-type regulator <br> Required for pathogenesis of Pseudomonas syringae","TvrR.hmm",300),
	UidR("UidR","TetR-type regulator <br> Regulator of the d-glucuronidase UidA of E. coli","UidR.hmm",250),
	UrdK("UrdK","TetR-type regulator <br> Located in the urdamycin biosynthesis cluster of Streptomyces fradiae","UrdK.hmm",260),
	VanT("VanT","TetR-type regulator <br> Global regulator of Vibrio (Listonella) anguillarum","VanT.hmm",250),
	VarR("VarR","TetR-type regulator <br> regulator of viriginiamycin biosynth in S. virginiae: (+) shot addition of 300 mug/L of VB-C; start the cultivation at 450 rpm and to continue until the DO concentration reached 80%. After reaching 80%, the DO concentration was maintained at this level by changing the agitation speed, up to a maximum of 800 rpm","VarR.hmm",250),
	VtpR("VtpR","TetR-type regulator <br> Global regulator of virulence factors of Vibrio tubiashii","VtpR.hmm",400),
	XdhR("XdhR","TetR-type regulator <br> Regulator of xanthine dehydrogenase of Streptomyces coelicolor","XdhR.hmm",350),
	YsiA("YsiA","TetR-type regulator <br> Regulator of fatty acid catabolism of Bacillus subtilis: Long-chain acyl-CoAs","YsiA.hmm",370),
	CymR("CymR","TetR-type regulator <br> Regulator of the cym and cmt operons required for p-cymene and p-cumate degradation of Pseudomonas putida: p-Cumate","CymR.hmm",100),
	
	// round 3
	AbrA1("AbrA1","Two-component <br> Sensor kinase in S. coelicolor: Iron","AbrA1.hmm",400),
	AbrA2("AbrA2","Two-component <br> Response regulator of S. coelicolor. Negative regulator of RED, ACT and CDA: AbrA1","AbrA2.hmm",300),
	CdaR("CdaR","Pathway-specific <br> CDA production in S. coelicolor","CdaR.hmm",600),
	CheA("CheA","Two-component <br> Histidine kinase for chemotaxis of E. coli: ATP","CheA.hmm",1000),
	CheB("CheB","Two-component <br> Response regulator in E.coli chemotaxis: CheA","CheB.hmm",650),
	CheV("CheV","Two-component <br> Response regulator in Bacillus subtilis. Chemotaxis related: CheA","CheV.hmm",330),
	CheW("CheW","Two-component <br> Response regulator in Bacillus subtilis. Chemotaxis related: CheA","CheW.hmm",125),
	CheY("CheY","Two-component <br> Response regulator of E. coli. Involved in the transmission of sensory signals from the chemoreceptors to the flagellar motors. In its active (phosphorylated or acetylated) form, CheY exhibits enhanced binding to a switch component, FliM, at the flagellar motor which induces a change from counterclockwise to clockwise flagellar rotation. Overexpression of CheY in association with MotA and MotB improves motility of a ycgR disruption, suggesting there is an interaction (direct or indirect) between the c-di-GMP-binding flagellar brake protein and the flagellar stator: Mg2+, CheA","CheY.hmm",195),
	CsrA("CsrA","Two-component <br> Carbon storage response regulator of E. coli.","CsrA.hmm",75),
	CyC_C("CyC-C","Two-component <br> Response regulator that is an adenylate cyclase in Arthrospira platensis","CyC-C.hmm",500),
	EcrE1("EcrE1","Two-component <br> Senory kinase of S. coelicolor: (+) co-cultivation with Corallococcus coralloides, or in inculum of 2.5% (v/v) B. subtilis","EcrE1.hmm",600),
	EnvZ("EnvZ","Two-component <br> Osmolarity sensor kinase of E. coli: Salt (HCl or others), ATP","EnvZ.hmm",900),
	FrzE("FrzE","Two-component <br> Sensor histidine kinase of Myxococcus xanthus. Involved in a sensory transduction pathway that controls the frequency at which cells reverse their gliding direction. FrzE seems to be capable of autophosphorylating itself on a histidine residue and then to transfer that group to an aspartate residue in the C-terminal part of the protein: Aspartate, ATP","FrzE.hmm",1000),
	FrzZ("FrzZ","Two-component <br> Response regulator of Myxococcus xanthus. Targets cell polarity axis: FrzE","FrzZ.hmm",350),
	GlnK("GlnK","Two-component <br> Sensor histidine kinase of Bacillus subtilis. Member of the two-component regulatory system GlnK/GlnL that positively regulates the expression of the glsA-glnT operon in response to glutamine. Probably activates GlnL by phosphorylation: Glutamine, ATP","GlnK.hmm",700),
	GlnL("GlnL","Two-component <br> Response regulator of Bacillus subtilis. Member of the two-component regulatory system GlnL/GlnK that positively regulates the expression of the glsA-glnT operon in response to glutamine. GlnL binds the promoter region of glsA-glnT in vitro: GlnK","GlnL.hmm",500),
	LysR("LysR","Two-component <br> Transcriptional activator protein  of E. coli. This protein activates the transcription of the lysA gene encoding diaminopimelate decarboxylase. LysR is also a negative regulator of its own expression.","LysR.hmm",130),
	LytS("LytS","Two-component <br> Sensor histidine kinase in Bacillus amyloliquefaciens: ATP","LytS.hmm",450),
	LytTR("LytTR","Two-component <br> Response regulator in Bacillus amyloliquefaciens: LytS","LytTR.hmm",300),
	NarL("NarL","Two-component <br> Nitrate/nitrite response regulator in E. coli: NarX or NarQ","NarL.hmm",260),
	NarP("NarP","Two-component <br> This protein activates the expression of the nitrate reductase (narGHJI) and formate dehydrogenase-N (fdnGHI) operons and represses the transcription of the fumarate reductase (frdABCD) operon in response to a nitrate/nitrite induction signal transmitted by either the NarX or NarQ proteins. In E. coli: NarX or NarQ","NarP.hmm",270),
	NarQ("NarQ","Two-component <br> Nitrate/nitrite sensor and phosphorlates NarL when nitrate/nitrile is present In E. coli: Nitrate/nitrite, ATP","NarQ.hmm",235),
	NarX("NarX","Two-component <br> Nitrate/nitrite sensor and phosphorlates NarL when nitrate/nitrile is present In E. coli: Nitrate/nitrite, ATP","NarX.hmm",300),
	NasR("NasR","Two-component <br> Positive regulator for nasFEDCBA operon expression in Klebsiella oxytoca: Nitrate/nitritie ","NasR.hmm",250),
	NtrB("NtrB","Two-component <br> Stress sensor, histidine kinase protein. Activated in low concentration of nitrogen. of Salmonella enterica: Nitrogen, ATP","NtrB.hmm",650),
	NtrC("NtrC","Two-component <br> Nitrogen-regulator protein of Salmonella enterica: NtrB","NtrC.hmm",650),
	OmpR("OmpR","Two-component <br> Response regulator in E. coli for outer membrane synthesis: EnvZ","OmpR.hmm",500),
	PhoP("PhoP","Two-component <br> Response regulator of S. coelicolor. OmpR-type. Positively regulates RED and ACT through ofsS+ropZ: PhoR, Mg2+","PhoP.hmm",200),
	PhoR("PhoR","Two-component <br> Sensor kinase of S. coelicolor: Phosphate","PhoR.hmm",750),
	PleC("PleC","Two-component <br> Histidine kinase of Caulobacter crescentus. Member of the two-component regulatory system involved in the regulation of polar organelle development. PleC functions as a membrane-associated protein kinase that transfers phosphate to the response regulator PleD, leading to its activation: ATP","PleC.hmm",1500),
	PleD("PleD","Two-component <br> Response regulator that is part of a signal transduction pathway controlling cell differentiation in the swarmer-to-stalked cell transition of Caulobacter crescentus.Catalyzes the condensation of two GTP molecules to the cyclic dinucleotide di-GMP (c-di-GMP), which acts as a secondary messenger: Mg2+","PleD.hmm",300),
	PrrA("PrrA","Two-component <br> Regulator of cell growth in Mycobacterium tuberculosis: PrrB","PrrA.hmm",300),
	PrrB("PrrB","Two-component <br> Sensor histidine kinase in Mycobacterium tuberculosis: ATP","PrrB.hmm",650),
	RpfC("RpfC","Two-component <br> Sensor kinase in Xanthomonas campestris pv. campestris. May also negatively regulate the production of DSF, independently of RpfG: Diffusible signaling factor (DSF), ATP","RpfC.hmm",350),
	RpfG("RpfG","Two-component <br> Response regulator in Xanthomonas campestris pv. campestris that degrades cyclic di-GMP, an unusual nucleotide second messenger, leading to the activation of Clp, a global transcriptional regulator that regulates a large set of genes in DSF pathway. May also directly control genes involved in biofilm dispersal: RpfC","RpfG.hmm",300),
	RsbU("RsbU","Two-component <br> Response regulator in Bacillus subtilis. Positive regulator to sigma-B: RsbT","RsbU.hmm",350),
	RsbV("RsbV","Two-component <br> Positive regulator of sigma-B activity in Bacillus subtilis. Non-phosphorylated RsbV binds to RsbW, preventing its association with sigma-B: RsbW","RsbV.hmm",70),
	RsbW("RsbW","Two-component <br> Negative regulator of sigma-B activity in Bacillus subtilis. Phosphorylates and inactivates its specific antagonist protein, RsbV. Upon phosphorylation of RsbV, RsbW is released and binds to sigma-B, thereby blocking its ability to form an RNA polymerase holoenzyme (E-sigma-B): ATP","RsbW.hmm",100),
	SCO0203("SCO0203","Two-component <br> Sensor kinase in S. coelicolor. ","SCO0203.hmm",1000),
	SCO0204("SCO0204","Two-component <br> Response regulator in S. coelicolor. Negative regulator of ACT: SCO0203","SCO0204.hmm",450),
	SCO3818("SCO3818","Two-component <br> Response regulator in S. coelicolor. Negative regulator of ACT: SCO0203","SCO3818.hmm",430),
	Spo0A("Spo0A","Two-component <br> Sporulation regulator for Bacillus subtilis: Calcium ","Spo0A.hmm",150),
	VieA("VieA","Two-component <br> Response regulator of Vibrio cholerae for biofilm formation: VieS","VieA.hmm",290),
	VieB("VieB","Two-component <br> Response regulator of Vibrio cholerae of unknown function: VieS","VieB.hmm",600),
	VieS("VieS","Two-component <br> Sensor histidine kinase of Vibrio cholerae: ATP, possibly amino acids/small peptides","VieS.hmm",500),
	YcbB("YcbB","Two-component <br> Response regulator of Bacillus subtilis. Member of the two-component regulatory system GlnL/GlnK that positively regulates the expression of the glsA-glnT operon in response to glutamine. GlnL binds the promoter region of glsA-glnT in vitro: GlnK","YcbB.hmm",170),
	YesM("YesM","Two-component <br> Sensor histidine kinase of Bacillus subtilis: Repressed by glucose. Activated by ATP","YesM.hmm",200),
	YesN("YesN","Two-component <br> Response regulator of Bacillus subtilis: YesM","YesN.hmm",300),
	
	//round 4 - regulators from Yong
	ClaR("ClaR","LysR-type <br> Positive regulator of clavulanic acid biosynthesis and neg. regulator of cephamycin C in Streptomyces clavuligerus","ClaR.hmm",120),
	PhoPs("PhoPs","Two-component <br> Response regulator of S. coelicolor. OmpR-type. Positively regulates RED and ACT through ofsS+ropZ: PhoR, Mg2+","PhoP(s).hmm",509),
	PhoRs("PhoRs","Two-component <br> Sensor kinase of S. coelicolor: Phosphate","PhoR(s).hmm",700),
	SpbR("SpbR","GBL-receptor <br> Pristinamycin prod. in S. pristinaspiralis (pleiotropic effects) involved in regulating pristinamycin biosynthesis and sporulation","SpbR.hmm",200),
	StgR("StgR","LysR-type <br> Negatively controls the expression of the redD and actII-orf4 genes encoding pathway specific 72 activators in S. coelicolor","StgR.hmm",220),
	TylP("TylP","GBL-receptor <br> Neg. control of tylQ /tylS and tylosin production in S. fradiae","TylP.hmm",125),
	TylQ("TylQ","SARP <br> Negative regulator of tylR and the downstream tylosin synthesis in S. fradiae","TylQ.hmm",60),
	TylR("TylR","SARP <br> Activator of tylosin synthesis genes in S. fradiae","TylR.hmm",200),
	TylS("TylS","SARP <br> Positive control of TylR in S. fradiae and tylosin production","TylS.hmm",300),
	
	AmphRI("AmphRI","LAL-type regulator for amphotericin in S. nodosus","AmphRI.hmm",1500),
	AmphRIII("AmphRIII","LAL-type regulator for amphotericin in S. nodosus","AmphRIII.hmm",1200),
	FkbN("FkbN","LAL-type activator of FK506 biosynthesis in S. tsukubaensis","FkbN.hmm",800),
	GdmRI("GdmRI","LAL-type regulator for geldanamycin in S. hygroscopicus","GdmRI.hmm",2000),
	GdmRII("GdmRII","LAL-type regulator for geldanamycin in S. hygroscopicus","GdmRII.hmm",700),
	MonH("MonH","Potential LAL-type activator of monensin biosynthesis in S. cinnamonensis","MonH.hmm",500),
	NbmM("NbmM","Putative LAL-type regulator in S. narbonesis","NbmM.hmm",545),
	NlmRI("NlmRI","Potential LAL-type regulator in S. nanchangensis","NlmRI.hmm",1200),
	NysRI("NysRI","LAL-type regulator for nystatin in S. noursei","NysRI.hmm",1200),
	NysRIII("NysRIII","LAL-type regulator for nystatin in S. noursei","NysRIII.hmm",840),
	PikD("PikD","LAL-type regulator on pikromycin in S. venezuelae","PikD.hmm",610),
	RapH("RapH","LAL-type regulator for rapamycin in S. hygroscopicus (ortholog, can't find the real one)","RapH.hmm",650),
	AlsR("AlsR","LTTR-type regulator <br> Local activator of acetoin synthesis in Bacillus subtilis: acetate","AlsR.hmm",550),
	AmpR("AmpR","LTTR-type regulator <br> Local activator of beta-lactamase in Rhodobacter capsulatus","AmpR.hmm",520),
	ArgP("ArgP","LTTR-type regulator <br> Local activator of arginine transprot in E. coli: arginine","ArgP.hmm",700),
	BenM("BenM","LTTR-type regulator <br> Global activator of aromatic compound degradation in Acinetobacter spp.: cis,cis- Muconate or benzoate","BenM.hmm",600),
	BlaA("BlaA","LTTR-type regulator <br> Local activator of beta-lactamase Streptomyces spp. ","BlaA.hmm",400),
	CatM("CatM","LTTR-type regulator <br> Global activator of catechol catabolism in Acinebactor baylyi: cis,cis-Muconate","CatM.hmm",600),
	CatR("CatR","LTTR-type regulator <br> Local repressor of catechol catabolism in Pseudomonas putida: cis,cis-Muconate","CatR.hmm",550),
	CbbR("CbbR","LTTR-type regulator <br> Global activator of carbon dioxide fixing in Xanthobacter flavus","CbbR.hmm",600),
	CfxR("CfxR","LTTR-type regulator <br> Global activator of carbon dioxide fixing in Alcaligenes eutrophus: auxotrophic growth conditions","CfxR.hmm",700),
	ChiR("ChiR","LTTR-type regulator <br> Local activator of chitiin binding/chitinase in Serratia marcescens","ChiR.hmm",650),
	CidR("CidR","LTTR-type regulator <br> Local activator of cid operon (murein hydrolase regulation) in Staphylococcus spp.: acetic acid","CidR.hmm",600),
	ClcR("ClcR","LTTR-type regulator <br> Local activator of chlorocatechol catabolism in Pseudomonas putida: cis,cis-Muconate","ClcR.hmm",600),
	CrgA("CrgA","LTTR-type regulator <br> Global activator/repressor of pili/capsule synthesis in Neisseria meningitidis: alpha-methylene-gama-butyrolactone","CrgA.hmm",600),
	CynR("CynR","LTTR-type regulator <br> Local activator of cyanate detoxification in E. coli: cyanate","CynR.hmm",550),
	CysB("CysB","LTTR-type regulator <br> Global activator of cysteine biosynthesis in Salmonella Typhimurium: N-acetylserine","CysB.hmm",350),
	CysL("CysL","LTTR-type regulator <br> Global activator of suphite reductase in Bacillus subtilis: sulphur source dependent","CysL.hmm",550),
	GltC("GltC","LTTR-type regulator <br> Local activator of glutamate synthase in Bacillus subtilis","GltC.hmm",600),
	HupR("HupR","LTTR-type regulator <br> Global activator of haem update in Vibrio vulnificus","HupR.hmm",500),
	HvrB("HvrB","LTTR-type regulator <br> Global activator of S-adenosyl-L-homocysteine hydrolase expression Rhodobacter capsulatus: light sensitivity","HvrB.hmm",450),
	IlvR("IlvR","LTTR-type regulator <br> Local activator of isoleucine/valine biosynthesis in Caulobacter crescentus","IlvR.hmm",500),
	IlvY("IlvY","LTTR-type regulator <br> Local activator of isoleucine/valine biosynthesis in E. coli: alpha-acetolactate or alpha-acetohydroxybutyrate","IlvY.hmm",300),
	IrgB("IrgB","LTTR-type regulator <br> Local activator of iron-regulated virulence factor in Vibrio cholerae","IrgB.hmm",520),
	LeuO("LeuO","LTTR-type regulator <br> Global activator/repressor of bacterial strigent response in Salmonella Typhimurium","LeuO.hmm",400),
	LrhA("LrhA","LTTR-type regulator <br> Global activator of flagella, motility and chemotaxis in E. coli","LrhA.hmm",539),
	MdcR("MdcR","LTTR-type regulator <br> Local activator of malonate catabolism in Klebsiella pneumoniae: malonate","MdcR.hmm",620),
	MetR("MetR","LTTR-type regulator <br> Global activator of methionine and cysteine transport/biosynthesis in Streptococccus salivarius: homocysteine","MetR.hmm",680),
	MleR("MleR","LTTR-type regulator <br> Local actvator of malolactic enzyme in Lactococcus lactis","MleR.hmm",450),
	MtaR("MtaR","LTTR-type regulator <br> Global activator of methionine transport in Streptococcus macedonicus","MtaR.hmm",500),
	MvfR("MvfR","LTTR-type regulator <br> Global activator of pathogenicity in Pseudomonas aeruginosa: 4-hydroxy-2-heptylquinone","MvfR.hmm",500),
	NagR("NagR","LTTR-type regulator <br> Local activator of naphthalene catabolism in Ralstonia eutropha: salicylate","NagR.hmm",600),
	NahR("NahR","LTTR-type regulator <br> Local activator of naphthalene/salicylate catabolism in Pseudomonas putida: salicyclate","NahR.hmm",500),
	NhaR("NhaR","LTTR-type regulator <br> Local activator of Na+/H+ antiporter in E. coli: Na+","NhaR.hmm",400),
	NocR("NocR","LTTR-type regulator <br> Local activator of nopaline catabolism in Argobacterium tumefaciens: octopine","NocR.hmm",700),
	NodD("NodD","LTTR-type regulator <br> Global activator of nitrogen fixation/symbiosis in Rhizobium spp","NodD.hmm",300),
	OccR("OccR","LTTR-type regulator <br> Local activator of octopine catabolism in Agrobacterium tumefaciens: octopine","OccR.hmm",275),
	OxyR("OxyR","LTTR-type regulator <br> Global activator of oxidative stress response (H-peroxide) in E. coli: redox changes","OxyR.hmm",480),
	PhcA("PhcA","LTTR-type regulator <br> Global activator of virulence regulator in Pseudomonas solanacearum","PhcA.hmm",590),
	QseA("QseA","LTTR-type regulator <br> Global activator of quorum sensing in E. coli","QseA.hmm",730),
	RbcR("RbcR","LTTR-type regulator <br> Local activator of carbon dioxide fixing in Chromatium vinosum ","RbcR.hmm",600),
	RovM("RovM","LTTR-type regulator <br> Global repressor of invasion/motility/virulence in Yersinia pestis","RovM.hmm",600),
	SpvR("SpvR","LTTR-type regulator <br> Local activator of virulence factor synthesis in Salmonella dublin","SpvR.hmm",600),
	SyrM("SyrM","LTTR-type regulator <br> Global activator of exopolysaccharide synthesis in Rhizobium meliloti","SyrM.hmm",400),
	TcbR("TcbR","LTTR-type regulator <br> Local activator of chlorocatechol metabolism in Pseudomonas sp. : 2-chloromuconic acid","TcbR.hmm",600),
	ToxR("ToxR","LTTR-type regulator <br> Local activator of quorum sensing in Burkholderia glumae: toxoflavin","ToxR.hmm",600),
	YofA("YofA","LTTR-type regulator <br> Local activator of cell division in Bacillus subtilis ","YofA.hmm",450)	
	;
	
	private final String abbreviation;
	private final String name;
	private final String hmm;
	private final double cutoff;
	
	private RegulatorDomains(final String abbreviation, final String name, final String hmm, final double cutoff) {
		this.abbreviation = abbreviation;
		this.name = name;
		this.hmm = hmm;
		this.cutoff = cutoff;
	}
	
	public final String abbreviation() {
		return abbreviation;
	}
	
	public final String fullName() {
		return name;
	}
	
	public final String hmm() {
		return hmm;
	}
	
	public final double cutoff() {
		return cutoff;
	}
	
	public DomainFamilies family() {
		return DomainFamilies.REGULATOR;
	}
	
	public static RegulatorDomains getRegulatorDomainFromAbbreviation(String abv){
		for(RegulatorDomains currentEnum : RegulatorDomains.values()) {
			if(abv.equals(currentEnum.abbreviation())) {
				return(currentEnum);
			}
		}
		System.err.println("Warning: regulator domain " + abv + " does not exist!.");
		return(null);
	}

}
